name: 'songstreams'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'songstreams'

# paths (folders) to sections of the dbt project
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  songstreams:
    staging:
      +materialized: table
      +enabled: true
      +tags: staging
      +schema: staging
    production:
      +materialized: table
      +enabled: true
      +schema: production

