table_columns = {
    "listen_events": """
        _id INTEGER IDENTITY PRIMARY KEY,
        artist VARCHAR NOT NULL,
        song VARCHAR NOT NULL,        
        session_id BIGINT NOT NULL,
        auth VARCHAR NOT NULL,
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        longitude GEOMETRY,
        latitude GEOMETRY,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender CHAR,
        registration BIGINT,
        timestamp BIGINT NOT NULL,
        abs_date DATE SORTKEY NOT NULL,
        year DATE DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """,
    "page_views": """
        _id INTEGER IDENTITY PRIMARY KEY,
        page VARCHAR NOT NULL,
        method: VARCHAR NOT NULL,
        status: INTEGER NOT NULL,
        session_id BIGINT NOT NULL,
        auth VARCHAR NOT NULL,
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        longitude GEOMETRY,
        latitude GEOMETRY,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender CHAR,
        registration BIGINT,
        timestamp BIGINT NOT NULL,
        abs_date DATE SORTKEY NOT NULL,
        year DATE DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """,
    "auth_events": """
        _id INTEGER IDENTITY PRIMARY KEY,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender CHAR,
        success BOOLEAN,
        longitude GEOMETRY,
        latitude GEOMETRY,
        session_id INTEGER NOT NULL,        
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        registration BIGINT,
        timestamp BIGINT NOT NULL,
        abs_date DATE SORTKEY NOT NULL,
        year DATE DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """
}
