table_columns = {
    "listen_events": """
        _id BIGINT IDENTITY(1, 1) PRIMARY KEY,
        artist VARCHAR NOT NULL,
        song VARCHAR NOT NULL,        
        session_id BIGINT NULL,
        auth VARCHAR NOT NULL,
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        longitude DOUBLE PRECISION NULL,
        latitude DOUBLE PRECISION NULL,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender VARCHAR,
        registration BIGINT,
        timestamp VARCHAR NULL,
        abs_date VARCHAR SORTKEY NOT NULL,
        year INTEGER DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """,
    "page_view_events": """
        _id BIGINT IDENTITY(1, 1) PRIMARY KEY,
        page VARCHAR NOT NULL,
        method VARCHAR NOT NULL,
        status INTEGER NOT NULL,
        session_id BIGINT NULL,
        auth VARCHAR NOT NULL,
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        artist VARCHAR NOT NULL,
        song VARCHAR NOT NULL,    
        duration DOUBLE PRECISION,
        longitude DOUBLE PRECISION NULL,
        latitude DOUBLE PRECISION NULL,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender VARCHAR,
        registration BIGINT,
        timestamp VARCHAR NULL,
        abs_date VARCHAR SORTKEY NOT NULL,
        year INTEGER DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """,
    "auth_events": """
        _id BIGINT IDENTITY(1,1) PRIMARY KEY,
        user_id INTEGER,
        last_name VARCHAR NOT NULL,
        first_name VARCHAR NOT NULL,
        gender VARCHAR,
        success BOOLEAN,
        longitude DOUBLE PRECISION NULL,
        latitude DOUBLE PRECISION NULL,
        session_id INTEGER NULL,        
        level VARCHAR NOT NULL,
        item_in_session INTEGER NOT NULL,
        city VARCHAR NOT NULL,
        zip INTEGER,
        state VARCHAR,
        user_agent VARCHAR,
        registration BIGINT,
        timestamp VARCHAR NULL,
        abs_date VARCHAR SORTKEY NOT NULL,
        year INTEGER DISTKEY NOT NULL,
        month SMALLINT,
        hour SMALLINT,
        day SMALLINT,
        day_of_week SMALLINT,
        is_weekend BOOLEAN
    """
}
